/**
 * App shell worker — precaches the built shell so a reload boots with no network.
 *
 * The worker itself is generated by vite-plugin-pwa. It only precaches, so API
 * responses and map tiles stay with offlineFetch and the tile cache.
 */

import { Button } from '@mantine/core';
import { notifications } from '@mantine/notifications';
import { isOnline } from './network';

const WORKER_URL = '/sw.js';
const UPDATE_NOTIFICATION_ID = 'app-shell-update';
const UPDATE_CHECK_INTERVAL_MS = 60 * 60 * 1000;

/** Register the app shell worker — call once at app startup */
export function registerAppShellWorker(): void {
  // an insecure origin still has the property, holding undefined
  if (!navigator.serviceWorker) return;

  // a worker from a production build on the same host would serve stale
  // precached chunks over the dev server, so dev tears them down instead
  if (import.meta.env.DEV) {
    navigator.serviceWorker.getRegistrations().then((registrations) => {
      for (const registration of registrations) registration.unregister();
    });
    return;
  }

  navigator.serviceWorker.register(WORKER_URL).then((registration) => {
    watchForWaitingWorker(registration);
    scheduleUpdateChecks(registration);
  });
}

function watchForWaitingWorker(registration: ServiceWorkerRegistration): void {
  if (registration.waiting) {
    promptForReload(registration);
    return;
  }
  registration.addEventListener('updatefound', () => {
    const installing = registration.installing;
    if (!installing) return;
    installing.addEventListener('statechange', () => {
      // no controller means this is the first install, there is nothing to replace
      if (installing.state === 'installed' && navigator.serviceWorker.controller) {
        promptForReload(registration);
      }
    });
  });
}

function scheduleUpdateChecks(registration: ServiceWorkerRegistration): void {
  async function checkForUpdate() {
    if (!isOnline()) return;
    await registration.update();
    // re-prompts a tab whose owner dismissed the notice and kept working
    if (registration.waiting) promptForReload(registration);
  }

  setInterval(checkForUpdate, UPDATE_CHECK_INTERVAL_MS);
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'visible') checkForUpdate();
  });
}

function promptForReload(registration: ServiceWorkerRegistration): void {
  notifications.show({
    id: UPDATE_NOTIFICATION_ID,
    title: 'New version available',
    message: (
      <Button size="xs" mt="xs" onClick={() => activateWaitingWorker(registration)}>
        Reload
      </Button>
    ),
    color: 'violet',
    autoClose: false,
  });
}

function activateWaitingWorker(registration: ServiceWorkerRegistration): void {
  navigator.serviceWorker.addEventListener('controllerchange', () => window.location.reload(), {
    once: true,
  });
  registration.waiting?.postMessage({ type: 'SKIP_WAITING' });
}
