#!/usr/bin/env bash
# one-command bring-up of the full GeoLang platform stack, including data prep.
# usage: scripts/platform-up.sh [geofabrik-extract-url]
set -euo pipefail
cd "$(dirname "$0")/.."

PBF_URL="${1:-https://download.geofabrik.de/europe/monaco-latest.osm.pbf}"

if [ ! -d ../geolang ]; then
  echo "missing sibling repos; run scripts/clone-geolang.sh first" >&2
  exit 1
fi
if [ ! -f ../geolang/.env ]; then
  echo "missing ../geolang/.env (LLM API keys); create it before bring-up" >&2
  exit 1
fi
if [ ! -d ../../Aavaaz/aavaaz ]; then
  echo "missing Aavaaz checkout at ../../Aavaaz/aavaaz (speech service)" >&2
  exit 1
fi

# PLATFORM_JWT_SECRET is one HS256 secret for every service that validates JWTs
# (ptolemy, tiletopia, collecta), so tokens minted by one are accepted by the
# others. GEOLANG_EXECUTOR_SECRET is what geolang-api presents to
# geolang-executor. Generated once and reused, so restarts don't invalidate
# sessions, and appended one at a time so a stack brought up before a variable
# existed picks it up. Never printed, never committed.
ENV_PLATFORM=.env.platform
generate_secret() {
  grep -qs "^$1=..*" "$ENV_PLATFORM" && return 0
  echo "generating $1 into $ENV_PLATFORM"
  # subshell keeps the tightened umask off the data dir created below
  (
    umask 077
    [ -s "$ENV_PLATFORM" ] ||
      echo "# generated by scripts/platform-up.sh - do not commit" > "$ENV_PLATFORM"
    echo "$1=$(openssl rand -base64 48 | tr -d '\n')" >> "$ENV_PLATFORM"
  )
}
generate_secret PLATFORM_JWT_SECRET
generate_secret GEOLANG_EXECUTOR_SECRET
COMPOSE=(docker compose --env-file "$ENV_PLATFORM" -f docker-compose.platform.yml)

mkdir -p data
# Marker of the region the derived data was built from. When the requested pbf
# differs (or the pbf is missing), re-fetch and invalidate the stale routing
# graph so itinera rebuilds it; geokode re-ingests the pbf on the recreate below.
# Same region requested again -> keep the pbf and graph.bin, no rebuild.
REGION_MARKER=data/.region-url
REGION_CHANGED=0
if [ "$(cat "$REGION_MARKER" 2>/dev/null || true)" != "$PBF_URL" ] || [ ! -f data/region.osm.pbf ]; then
  echo "region changed -> downloading OSM extract: $PBF_URL"
  curl -fL "$PBF_URL" -o data/region.osm.pbf.tmp
  mv -f data/region.osm.pbf.tmp data/region.osm.pbf
  rm -f data/graph.bin
  printf '%s\n' "$PBF_URL" > "$REGION_MARKER"
  REGION_CHANGED=1
else
  echo "region unchanged ($PBF_URL); reusing data/region.osm.pbf and graph.bin"
fi

# containers left over from an earlier (or renamed) project keep stale network
# references around, which makes `up` fail with "network not found"
"${COMPOSE[@]}" down --remove-orphans
"${COMPOSE[@]}" up -d --build

echo "waiting for services to report healthy..."
for _ in $(seq 1 60); do
  starting=$("${COMPOSE[@]}" ps --format '{{.Health}}' | grep -c starting || true)
  [ "$starting" -eq 0 ] && break
  sleep 5
done

# itinera builds its routing graph from the pbf on first start (or after a region
# change invalidated graph.bin); for a big metro that import runs for minutes and
# the container reports unhealthy meanwhile. Wait on the router and geocoder
# directly so a fresh region fully takes effect before we seed / declare ready.
echo "waiting for geokode + itinera to answer (graph build can take minutes)..."
for probe in "geokode http://localhost:3001/health" "itinera http://localhost:3002/health"; do
  name=${probe%% *}; url=${probe#* }
  for _ in $(seq 1 96); do
    curl -fsS "$url" >/dev/null 2>&1 && { echo "  $name ready"; break; }
    sleep 5
  done
done
echo "waiting for aavaaz to answer (model download can take minutes)..."
for _ in $(seq 1 96); do
  "${COMPOSE[@]}" exec -T aavaaz curl -fsS http://localhost:8000/health >/dev/null 2>&1 && { echo "  aavaaz ready"; break; }
  sleep 5
done
"${COMPOSE[@]}" ps --format 'table {{.Name}}\t{{.Status}}'

if [ -f scripts/seed-parcels.mjs ]; then
  echo "seeding real-estate demo data..."
  # on a region change, wipe the previous region's demo features so they don't
  # linger at the old coordinates; the seed re-anchors on the new region.
  SEED_RESET=$([ "$REGION_CHANGED" = 1 ] && echo 1 || true) \
    node scripts/seed-parcels.mjs || echo "seed failed (ptolemy not ready yet?); rerun: node scripts/seed-parcels.mjs"
fi

echo
echo "viewer:  http://localhost:5174"
echo "agent:   http://localhost:5174/agent/health"
echo "speech:  http://localhost:5174/speech/health"
echo "jupyter: http://localhost:5174/jupyter/api"
