#!/usr/bin/env bash
# one-command bring-up of the full GeoLang platform stack, including data prep.
# usage: scripts/platform-up.sh [geofabrik-extract-url]
set -euo pipefail
cd "$(dirname "$0")/.."

PBF_URL="${1:-https://download.geofabrik.de/europe/monaco-latest.osm.pbf}"

if [ ! -d ../geolang ]; then
  echo "missing sibling repos; run scripts/clone-geolang.sh first" >&2
  exit 1
fi
if [ ! -f ../geolang/.env ]; then
  echo "missing ../geolang/.env (LLM API keys); create it before bring-up" >&2
  exit 1
fi

# one HS256 secret for every service that validates JWTs (ptolemy, tiletopia,
# collecta): tokens minted by one are accepted by the others. Generated once and
# reused, so restarts don't invalidate sessions. Never printed, never committed.
ENV_PLATFORM=.env.platform
if ! grep -qs '^PLATFORM_JWT_SECRET=..*' "$ENV_PLATFORM"; then
  echo "generating $ENV_PLATFORM (shared JWT secret)"
  # subshell keeps the tightened umask off the data dir created below
  (
    umask 077
    {
      echo "# generated by scripts/platform-up.sh - do not commit"
      echo "PLATFORM_JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n')"
    } > "$ENV_PLATFORM"
  )
fi
COMPOSE=(docker compose --env-file "$ENV_PLATFORM" -f docker-compose.platform.yml)

mkdir -p data
if [ ! -f data/region.osm.pbf ]; then
  echo "downloading OSM extract: $PBF_URL"
  curl -fL "$PBF_URL" -o data/region.osm.pbf
fi

# containers left over from an earlier (or renamed) project keep stale network
# references around, which makes `up` fail with "network not found"
"${COMPOSE[@]}" down --remove-orphans
"${COMPOSE[@]}" up -d --build

echo "waiting for services to report healthy..."
for _ in $(seq 1 60); do
  starting=$("${COMPOSE[@]}" ps --format '{{.Health}}' | grep -c starting || true)
  [ "$starting" -eq 0 ] && break
  sleep 5
done
"${COMPOSE[@]}" ps --format 'table {{.Name}}\t{{.Status}}'

if [ -f scripts/seed-parcels.mjs ]; then
  echo "seeding real-estate demo data..."
  node scripts/seed-parcels.mjs || echo "seed failed (ptolemy not ready yet?); rerun: node scripts/seed-parcels.mjs"
fi

echo
echo "viewer:  http://localhost:5174"
echo "agent:   http://localhost:5174/agent/health"
echo "jupyter: http://localhost:5174/jupyter/api"
